// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5VRi7v8AjtZBFwZSNvmTt6V6b3M3lo1c',
    appId: '1:773843122627:web:c8e3faf8aa5f924c8be576',
    messagingSenderId: '773843122627',
    projectId: 'hcode-spor-takip-programi',
    authDomain: 'hcode-spor-takip-programi.firebaseapp.com',
    storageBucket: 'hcode-spor-takip-programi.appspot.com',
    measurementId: 'G-07N4EGE5CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5l_y6CU2G4bLIUXgE4QwW6l71CtmsOVc',
    appId: '1:773843122627:android:82f7bd11dd43f5c48be576',
    messagingSenderId: '773843122627',
    projectId: 'hcode-spor-takip-programi',
    storageBucket: 'hcode-spor-takip-programi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4h1MRAiLn52XjdwZdYciCnMKt-1wxtxM',
    appId: '1:773843122627:ios:9adec29ba4212f528be576',
    messagingSenderId: '773843122627',
    projectId: 'hcode-spor-takip-programi',
    storageBucket: 'hcode-spor-takip-programi.appspot.com',
    iosBundleId: 'com.hcode.sporTakipUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4h1MRAiLn52XjdwZdYciCnMKt-1wxtxM',
    appId: '1:773843122627:ios:9adec29ba4212f528be576',
    messagingSenderId: '773843122627',
    projectId: 'hcode-spor-takip-programi',
    storageBucket: 'hcode-spor-takip-programi.appspot.com',
    iosBundleId: 'com.hcode.sporTakipUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5VRi7v8AjtZBFwZSNvmTt6V6b3M3lo1c',
    appId: '1:773843122627:web:41f36825be7b8f068be576',
    messagingSenderId: '773843122627',
    projectId: 'hcode-spor-takip-programi',
    authDomain: 'hcode-spor-takip-programi.firebaseapp.com',
    storageBucket: 'hcode-spor-takip-programi.appspot.com',
    measurementId: 'G-9RB92S1PLJ',
  );
}